apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{- include "cert-exporter.fullname" . -}}-cert-manager"
  labels:
    {{- include "cert-exporter.certManagerDeploymentLabels" . | nindent 4 }}
spec:
  replicas: {{ .Values.certManagerDeployment.deployment.replicaCount }}
  selector:
    matchLabels:
      {{- include "cert-exporter.certManagerDeploymentSelectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "cert-exporter.certManagerDeploymentSelectorLabels" . | nindent 8 }}
      annotations:
        {{- toYaml .Values.certManagerDeployment.deployment.podAnnotations | nindent 8 }}
    spec:
    {{- with .Values.certManagerDeployment.deployment.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "cert-exporter.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.certManagerDeployment.deployment.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.certManagerDeployment.deployment.securityContext | nindent 12 }}
          image: "{{ .Values.certManagerDeployment.deployment.image.repository  }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.certManagerDeployment.deployment.image.pullPolicy }}
          {{- with .Values.certManagerDeployment.deployment.image.command  }}
          command:
            {{- toYaml . | nindent 12}}
          {{- end}}
          {{- with .Values.certManagerDeployment.deployment.image.args  }}
          args:
            {{- toYaml . | nindent 12}}
          {{- end}}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            {{- toYaml .Values.certManagerDeployment.deployment.resources | nindent 12 }}
          volumeMounts:
           {{- toYaml .Values.certManagerDeployment.deployment.volumeMounts | nindent 12 }}
      {{- with .Values.certManagerDeployment.deployment.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.certManagerDeployment.deployment.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.certManagerDeployment.deployment.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      volumes:
          {{- toYaml .Values.certManagerDeployment.deployment.volumes | nindent 8 }}
